### ISSUE TITLE
bug: Missing become: yes on teardown

### ISSUE THREAD

**Issue by mtraynham** [MonolithProjects/ansible-github_actions_runner#135]
### Summary

When I try to teardown a runner, I get an error.  I don't see the error because it's got a `no_log` statement.  I removed the `no_log` statement and it's saying:
> Must not run with sudo

This particular command is missing a `become: yes` attribute on the module invocation, https://github.com/MonolithProjects/ansible-github_actions_runner/blob/master/tasks/uninstall_runner.yml#L19-L25

### Issue Type

Bug Report

### Ansible Version

```console
ansible 2.10.17
  python version = 3.8.12 (default, Jan 10 2022, 20:02:19) [GCC 9.3.0]
```

### Steps to Reproduce

- Spin it up and tear it down with `runner_state: absent`

### Expected Results

It does not error.

### Actual Results

```console
TASK [monolithprojects.github_actions_runner : Unregister runner from the GitHub] ************************************************************************************
fatal: [amd64]: FAILED! => {"changed": true, "cmd": ["./config.sh", "remove", "--token", "REDACTED", "--name", "foobar", "--unattended"], "delta": "0:00:00.004886", "end": "2022-06-02 16:21:57.406664", "msg": "non-zero return code", "rc": 1, "start": "2022-06-02 16:21:57.401778", "stderr": "", "stderr_lines": [], "stdout": "Must not run with sudo", "stdout_lines": ["Must not run with sudo"]}
```
```

**Comment by MonolithProjects** [comment]
Fixed in #136
