### ISSUE TITLE
feature: use ansible_facts

### ISSUE THREAD

**Issue by jackhodgkiss** [MonolithProjects/ansible-github_actions_runner#176]
### Summary

Some users of this role may desire to run the role with `inject_facts_as_vars = False` in their `ansible.cfg`.

The motivation of preventing facts being injected as variables would be to avoid performance penalties that would incurred by having 100s of variables per host within the global namespace.

Each use of `ansible_` would be replaced with their `ansible_facts` counterpart such `ansible_hostname` be written as `ansible_facts.hostname`

https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html#ansible-facts

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Issue was resolved in https://github.com/MonolithProjects/ansible-github_actions_runner/pull/177
