### ISSUE TITLE
Become user tasks may fail under ubuntu-focal

### ISSUE THREAD

**Issue by lanefu** [MonolithProjects/ansible-github_actions_runner#20]
https://github.com/MonolithProjects/ansible-github_actions_runner/blob/2e61b3654be998869ad59672143e91c62c768d9c/tasks/install_runner.yml#L59

Using ubuntu-focal-cloud image I had become_user tasks fail with this error

```
FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: changing ownership of '/var/tmp/ansible-tmp-1592709642.9458294-6991-199301742827418/': Operation not permitted\nchown: changing ownership of '/var/tmp/ansible-tmp-1592709642.9458294-6991-199301742827418/AnsiballZ_command.py': Operation not permitted\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

resolution is to install `acl` package.

doesn't happen with ubuntu-bionic-cloud

**Comment by MonolithProjects** [comment]
Hi, thanks for letting me know. However i was unable to reproduce your issue. I tested it with Ubuntu 20.04 KVM image 20200618. But for me the `acl` was already there after the first boot (maybe installed by cloud-init as a some dependency as i do not see it in the manifest file). Anyway... i will keep the issue open and check it again tomorrow. For now please use Ansible `pre_tasks` to install `acl`.

**Comment by MonolithProjects** [comment]
`acl` package added
