### ISSUE TITLE
Cache downloaded github runners tar locally?

### ISSUE THREAD

**Issue by vrga** [MonolithProjects/ansible-github_actions_runner#48]
Hi, just one slight quibble with this role, downloading the github actions tar is very sluggish, 2.5MB/s on a 15MB/s line, due to github presumably throttling this.

Would it be possible to define a local download cache dir for the tar so that it does not need to get redownloaded on every run if installing from scratch?

**Comment by MonolithProjects** [comment]
Hi there... I downloaded the package in 5.5sec, so i don't think there is some crazy throttling in place.

But anyway i think the current behavior makes no sense. If the package was already downloaded, then why to download it again. I will change it :)

**Comment by vrga** [comment]
It might as well be my home ISP having some issues or throttling, but yes the current way of "always download then throw away is wasteful".

Thank you for a great ansible role :)

**Comment by MonolithProjects** [comment]
Yeah..can be :) OK the fix for your issue can be found in release [1.4.5](https://github.com/MonolithProjects/ansible-github_actions_runner/releases/tag/1.4.5) (already in Ansible Galaxy). It should help...

**Comment by vrga** [comment]
Can confirm it works, thank you very much once again :)
