### ISSUE TITLE
Labels seem to be broken

### ISSUE THREAD

**Issue by vandlol** [MonolithProjects/ansible-github_actions_runner#77]
`runner_labels: "Ubuntu"` -> creates label Ubuntu
`runner_labels: "pr-4"` -> creates labels p, r, -, and 4

```
runner_labels: 
	- Ubuntu
	- pr-4	
```		
-> creates label: ["Ubuntu", "pr-4"]

`runner_labels: ["pr-4"]` -> creates label pr-4

**Comment by MonolithProjects** [comment]
Hi @vandlol , thanks for your issue. Labels must to be defined as a [list variable](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#list-variables) , not as a [simple string variable](https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#simple-variables).

I tested your labels with role release 1.8.2:
```
runner_labels: 
	- Ubuntu
	- pr-4	
```
The outcome is:
![repo](https://user-images.githubusercontent.com/19806716/117953618-7cd63e80-b316-11eb-82a7-27717174d91d.png)

**Comment by vandlol** [comment]
okay, tested this again and a yml list, like you tested seems to work now.
but just to be clear, a string should work as well, but the way you implemented this
https://github.com/MonolithProjects/ansible-github_actions_runner/blob/5d619de471da360b948cf840f747a5e243fc9b0f/tasks/install_runner.yml#L80
this will either join a List using "," or split a string and join the letters using ",".

**Comment by MonolithProjects** [comment]
Got your point. But there is no simple solution for this (except to place the labels into the list - even it's a single value). The behavior of the join() filter is that if you provide a single string, the filter will join all characters of the string with a value provided in the filter. And for example if i would do let say `{{ runner_labels | list | join(',') }}`, the outcome would be the same as for a single string the `list` will return a list of characters https://jinja2docs.readthedocs.io/en/stable/templates.html?highlight=join#list

But if you see some quick fix, feel free to open a PR.

**Comment by MonolithProjects** [comment]
Closing this issue
