### ISSUE TITLE
uri and command modules cause failures in check mode

### ISSUE THREAD

**Issue by adamsilkcm** [MonolithProjects/ansible-github_actions_runner#82]
Ansible uri module does not support check mode and is skipped when running in check mode.  Command module also acts the same without a creates or removes.

Because of this, running with --check always fails.

**Task Find the latest runner version (RUN ONCE)** does not populate api_response, so **Set runner_version variable (if it is latest)** fails due to the undefined variable: ` msg: The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'json'`

Similarly, the collect_info_org and collect_info_repo tasks cause failures because registered_runners is never populated by **Check currently registered runners (RUN ONCE)**

Adding `check_mode: false` to the information gathering steps will cause them to run even in check mode, populate the variables, and eliminate the failures.

**Comment by MonolithProjects** [comment]
Thanks! Now it's fixed in release [1.8.4](https://github.com/MonolithProjects/ansible-github_actions_runner/tree/1.8.4)
