### ISSUE TITLE
Documentation:  Using a "GitHub App" to register a runner

### ISSUE THREAD

**Issue by dstratman-fi** [MonolithProjects/ansible-github_actions_runner#86]
Hi Team,

Just something we are looking into on our end... our security team prefers we do not use a user PAT to register a self-hosted github runner at the org level.  We would like to use the GitHub app method for security. 

Has that been tested on this role?  Is there some documentation that would show any differences / changes in implementation with that in mind?  I have tested this zero so far and have only tested with the PAT-based method from a user account at the org level.

Thanks!

**Comment by MonolithProjects** [comment]
Hi there... The PAT is being used to authenticate the user which will then generate time-limited token which is being used for the Runner registration. The Role is using the [same](https://github.com/MonolithProjects/ansible-github_actions_runner/blob/bc602e2a760f0a5bae2212e1d28968029af3361a/tasks/collect_info_org.yml#L4) header in the GitHub API call as when you are authenticating using the OAuth2 token. So it should work, but i never tested it... However, i don't this this an option in Github Actions Runner Documentation https://docs.github.com/en/actions/hosting-your-own-runners/adding-self-hosted-runners
