### ISSUE TITLE
Please remove regex for ghp_ token

### ISSUE THREAD

**Issue by vandlol** [MonolithProjects/ansible-github_actions_runner#95]
This change just broke the playbook for me.
My perfectly alright token is no longer working.
Also, if you need to check for a token prefix (which seems odd to me) please check for all of the prefixes: 
ghp for GitHub personal access tokens
gho for OAuth access tokens
ghu for GitHub user-to-server tokens
ghs for GitHub server-to-server tokens
ghr for refresh tokens
I am using your Playbook on a Github Enterprise Server which does not need any prefixes for tokens.
Please make this optional or something.

Cheers

**Comment by MonolithProjects** [comment]
Hmm you are right about the token on Github Enterprise Server. I was not thinking about it when i was merging https://github.com/MonolithProjects/ansible-github_actions_runner/pull/93 Gonna fix it...

**Comment by MonolithProjects** [comment]
done https://github.com/MonolithProjects/ansible-github_actions_runner/pull/96
