### ISSUE TITLE
runner_org option fail on version 1.11.1

### ISSUE THREAD

**Issue by leonid-granulate** [MonolithProjects/ansible-github_actions_runner#97]
When setting `runner_org: true` i've got the following error:
```
TASK [monolithprojects.github_actions_runner : Check runner_org variable (RUN ONCE)] ***************************************************************************************************************************************************
fatal: [prod-ci-cd-001]: FAILED! => {
    "assertion": "runner_org == True or runner_org == False",
    "changed": false,
    "evaluated_to": false,
    "msg": "runner_org should be a boolean value"
}
```

I've tried to set `True`, `yes`, `'yes'`, same behavior

**Comment by MonolithProjects** [comment]
Hi @leonid-granulate ... strange as i can not reproduce your issue. Also the scheduled Molecule test looks [ok](https://github.com/MonolithProjects/ansible-github_actions_runner/runs/3332174791?check_suite_focus=true#step:4:88) What Ansible release are you using? Can you share a snipped of your playbook where you are defining this variable?

**Comment by MonolithProjects** [comment]
Closing due to no response (3wks). If you still have problem with this issue, please reopen it.
