### ISSUE TITLE
Wrong parsing of runner_labels

### ISSUE THREAD

**Issue by leonid-granulate** [MonolithProjects/ansible-github_actions_runner#98]
When passing a list of labels to `runner_labels`, the labels are treated as string.
For example:
```yaml
runner_labels:
  - label
  - test
```
Will appear in github as `'l', 'a', 'b', 'e', 't', 's'`
![image](https://user-images.githubusercontent.com/79204715/129685409-193b20d4-ec67-46f1-b6b8-e44c5c5fd12d.png)

Version: 1.9.0 (1.11.1 not worked for me while using `runner_org: true`, see https://github.com/MonolithProjects/ansible-github_actions_runner/issues/97)

**Comment by MonolithProjects** [comment]
This issue was already resolved in newer releases
